local codes = {
    "AnniEventWEEK!!",
    "DAILYRewards?!",
    "AnniDungeonRelease!",
    "Happy1stAnni!!",
    "AnniUpdSoon?!",
    "AnimeLastDelay",
    "OtakuNoob2Pro!",
    "ShadowMonarch!",
    "Dungeons!",
    "AnotherSecretCode!",
    "SecretCode!",
    "NewUi!",
    "BattlepassReset!",
    "GreatWarWow!",
    "NewCaverns!",
    "NewGlobalBoss!",
    "SORRYforIssues!!",
    "NewGodly!",
    "ChristmasRaid!",
    "EventBP!",
    "Sub2OtakuGaming",
    "BossRush!",
    "SkinBanner!",
    "LateUpdSorry!",
    "BossIGCool!",
    "NewUpdateS00N",
    "Drops!",
    "Evos!",
    "Tournaments!"
}

return codes;
