local Cards = {
  Buff = {
    "+ Attack I",
    "+ Attack II",
    "+ Attack III",
    "+ Boss Damage I",
    "+ Boss Damage II",
    "+ Boss Damage III",
    "+ Gain 2 Random Effects Tier 1",
    "+ Gain 2 Random Effects Tier 2",
    "+ Gain 2 Random Effects Tier 3",
    "+ New Path",
    "+ Range I",
    "+ Range II",
    "+ Range III",
    "+ Yen I",
    "+ Yen II",
    "+ Yen III",
    "- Cooldown I",
    "- Cooldown II",
    "- Cooldown III",
    "- Active Cooldown I",
    "- Active Cooldown II",
    "- Active Cooldown III"
  },
  Debuff = {
    "+ Enemy Health I",
    "+ Enemy Health II",
    "+ Enemy Health III",
    "+ Enemy Shield I",
    "+ Enemy Shield II",
    "+ Enemy Shield III",
    "+ Enemy Speed I",
    "+ Enemy Speed II",
    "+ Enemy Speed III",
    "+ Explosive Deaths I",
    "+ Explosive Deaths II",
    "+ Explosive Deaths III"
  }
}

return Cards;
