local tabl = {
  'hidan_unit_evolved', 
  'stain_evolved',
  'dazai_evolved', 
  'alucard_evolved',
  'jotaro', 
  'eren_final', 
  'ainz_evolved', 
  'kisuke_evolved',
	'yamamoto_evolved', 
  'dio_heaven', 
  'aki_evolved', 
  'law_2_evolved', 
  'brook_evolved', 
  'gojo_evolved', 
  'pucci_heaven',
	'jotaro_p6_evolved', 
  'homura_evolved', 
  'diavolo', 
  'armin',
  'aizen_christmas',
  'gojo_evolved',
  'goku_ssj3_evolved',
  'vegeta_majin_evolved',
  'buddha_evolved'
}

return tabl;
