local uniqueCards = {
    "Ambush",
    "Avarice I",
    "Avarice II",
    "Chaos Eater",
    "Demon Takeover",
    "Emotional Damage",
    "Enraged I",
    "Enraged II",
    "Feeding Madness",
    "Fortune",
    "God Speed I",
    "God Speed II",
    "Godspeed",
    "Immolation",
    "Initiative I",
    "Initiative II",
    "Insanity",
    "Lethargy",
    "Loyalty I",
    "Loyalty II",
    "Metal Skin",
    "Opulence",
    "Raging Power",
    "Reconnaissance I",
    "Reconnaissance II",
    "Sluggish I",
    "Sluggish II",
    "Venoshock",
    "Weak Point I",
    "Weak Point II"
}

return uniqueCards;
