local Cards = { 
	[1] = "Ambush",
	[2] = "Avarice I",
	[3] = "Avarice II",
	[4] = "Chaos Eater",
	[5] = "Demon Takeover",
	[6] = "Emotional Damage",
	[7] = "Enraged I",
	[8] = "Enraged II",
	[9] = "Feeding Madness",
	[10] = "Fortune",
	[11] = "God Speed I",
	[12] = "God Speed II",
	[13] = "Godspeed",
	[14] = "Immolation",
	[15] = "Initiative I",
	[16] = "Initiative II",
	[17] = "Insanity",
	[18] = "Insanity",
	[19] = "Lethargy",
	[20] = "Loyalty I",
	[21] = "Loyalty II",
	[22] = "Metal Skin",
	[23] = "Metal Skin",
	[24] = "Opulence",
	[25] = "Raging Power",
	[26] = "Reconnaissance I",
	[27] = "Reconnaissance II",
	[28] = "Sluggish I",
	[29] = "Sluggish II",
	[30] = "Venoshock",
	[31] = "Weak Point I",
	[32] = "Weak Point II",
	} 

return Cards;
